config/routes.rb
Rails.application.routes.draw do

  get 'categories/index'

  get 'categories/show'

  get 'categories/update'

  get 'categories/destroy'

  get 'categories/new'

  get 'categories/edit'

  root to: 'pages#home'
  get '/bonjour(/:name)', to:'pages_#salut', as: 'salut'
  resources :posts
  resources :categories
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/concerns/sluggable.rb
module Sluggable

  extend ActiveSupport::Concern

  included do
    before_validation :set_default_slug, on: [:create, :update], if: '!slug.nil?'
    validates :slug, format: { with: /\A[a-z0-9\-]+\z/}, uniqueness: true

    private

    def set_default_slug
      if !self.name.nil? && !self.name.empty? && self.slug.empty?
        self.slug = name.parameterize
      end
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord

  include Sluggable

  scope :online, -> (online) { where(online: online)}
  scope :published, -> {where(online: 1)}
  scope :offline, -> {where(online: 0)}
  scope :alpha, -> {order(name: :asc)}

  def as_json(options = nil)
    super(only:[:name, :id, :created_at])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :danger
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @session = session[:user_id]
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    redirect_to category_path(@category.id)
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    redirect_to category_path(@category.id)
  end

  def edit
    @category = Category.find(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:name, :slug)
  end



end

app/controllers/pages_controller.rb
   class PagesController < ApplicationController


     def salut
       @name = params[:name]
     end

     def home

     end
   end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only:[:show, :edit, :update, :destroy]

  def index
    # permet l'affichage de msg d'alerte seulement une fois
    # flash.now[:success] = "Salut"
    @posts = Post.online(0).all
    respond_to do |format|
      format.html
      format.json {render json: @posts}
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json {render json: @post}

    end
  end

  def edit
  end

  def update
   if @post.update(post_params)
    redirect_to posts_path, success: "L'article à bien été modifié"
   else
     render 'edit'
     end
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.create(post_params)
    redirect_to post_path(post.id), success: "L'article à bien été créer"
  end

  def destroy
    @post.destroy
    redirect_to posts_path, success: "L'article à bien été supprimé"
  end

  private

  def post_params
    params.require(:post).permit(:name, :content, :slug)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1> Editer une Categorie</h1>

<%= form_for @category do |f| %>
    <div class="form-group">
      <%= f.text_field :name, placeholder: 'Nom de la catégorie', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.text_field :slug, placeholder: 'Url', class: 'form-control' %>
    </div>
    <div class="form-group">
      <button class="btn btn-primary" type="submit">Modifier la catégorie</button>
    </div>
<% end %>

app/views/categories/index.html.erb
<h1>
  les Categories</h1>

<p>
  Session : <%= @session.inspect %>
</p>

<table class="table">
  <thead>
  <tr>
    <td>Id</td>
    <tdn>Nom</tdn>
    <td>Actions</td>
  </tr>
  </thead>
  <tbody>
  <% @categories.each do |category| %>
  <tr>
    <td><%= category.id %></td>
    <td><%= category.name %></td>
    <td>
      <a href="<%= edit_category_path(category.id) %>" class="btn btn-primary">Editer</a>
      <a href="<%= category_path(category.id) %>" class="btn btn-danger" data-confirm="Supprimer ?" data-method="delete">Supprimer</a>
    </td>
  </tr>
  <% end %>
  </tbody>

</table>

<p>
  <a href="<%= new_category_path %>" class="btn btn-success">Créer une nouvelle categorie</a>
</p>

app/views/categories/new.html.erb
<h1> Nouvelle Categorie</h1>

<%= form_for @category do |f| %>
    <div class="form-group">
      <%= f.text_field :name, placeholder: 'Nom de la catégorie', class: 'form-control' %>
    </div>
<div class="form-group">
  <%= f.text_field :slug, placeholder: 'Url', class: 'form-control' %>
</div>
<div class="form-group">
  <button class="btn btn-primary" type="submit">Créer la catégorie</button>
</div>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<p><a href="<%= categories_path %>" class="btn btn_primary">Retour aux categories</a></p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubyblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </head>

  <body>
  <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="<%= root_path %>">Mon site RoR</a>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= posts_path %>">Les Articles</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= categories_path %>">Les Catégories</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
 <div class="container" style="padding-top: 5rem;">
   <% flash.each do |name, msg| %>
       <div class="alert alert-<%= name %>"><%= msg %></div>
       <% end %>
    <%= yield %>
 </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Bienvenue sur mon tout premier site RoR</h1>
<p>C'est de la balle mec !</p>

app/views/pages/salut.html.erb
Salut <%= @name %> comment ça va ?

app/views/posts/edit.html.erb
<h1>Editer l'article</h1>

<% if @post.errors.any? %>
    <div class="alert alert-danger">
      <ul>
      <%@post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>
<%= form_for @post do |f| %>
    <div class="form-group">
      <label>Titre de l'article</label>
      <%= f.text_field :name, class: 'form-control' %>

    </div>

    <div class="form-group">
      <label>URL de l'article</label>
      <%= f.text_field :slug, class: 'form-control' %>

    </div>

    <div class="form-group">
      <label>Contenu de l'article</label>
      <%= f.text_area :content, class: 'form-control' %>
    </div>

    <div class="form-group">
      <button type="submit" class="btn btn-primary">Modifier l'article</button>
    </div>
    <% end %>

app/views/posts/index.html.erb
<h1>Articles du blog</h1>

<% @posts.each do |post| %>
    <h2><%= post.name %></h2>

   <p><%= post.content %></p>
    <p>
      <a href="<%= post_path(post.id) %>" class="btn btn-primary">Lire la suite</a>
      <a href="<%= edit_post_path(post.id) %>" class="btn btn-default">Editer</a>
      <a href="<%= post_path(post.id) %>" class="btn btn-danger" data-confirm="Etes-vous sûr?" data-method="DELETE">Supprimer</a>
    </p>
<% end %>

<p>
  <a href="<%=new_post_path %>" class="btn btn-success">Créer un article</a>
</p>

app/views/posts/new.html.erb
<h1>Créer l'article</h1>

<%= form_for @post do |f| %>
    <div class="form-group">
      <label>Titre de l'article</label>
      <%= f.text_field :name, class: 'form-control' %>

    </div>
    <div class="form-group">
      <label>Contenu de l'article</label>
      <%= f.text_area :content, class: 'form-control' %>
    </div>

    <div class="form-group">
      <button type="submit" class="btn btn-primary">Créer l'article</button>
    </div>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.name %></h1>

<p><%= @post.content %></p>

<p>
  <a href="<%= posts_path %>" class="btn btn-primary">Retour aux articles</a>
</p>